### ISSUE TITLE
Authentification system and discovery

### ISSUE THREAD

**Issue by AmarOk1412** [AmarOk1412/rori_core#1]
# Definition

## User
A user for **RORI** is someone who uses the system under an identity. For example, Alice (real person) can uses her phone, her computer linked to **RORI** under the identity *alice@rori* (user for RORI) and an IRC client as an anonymous user.

## Device
A device for **RORI** is a *ring_id*. This device can be linked to a specific user or to the *anonymous* user.

## Multi-devices
A user can uses as many as devices they want. The thing is, **RORI** can choose to interact with only one device of a user. For example, if Alice takes a picture and asks **RORI** to store the photo in a specific folder on her computer, we only have to interact with the endpoint on the computer, not all devices.

## Name-service
Each **RORI** embeds its own name-service. Doc is [here](https://tuleap.ring.cx/plugins/mediawiki/wiki/ring/index.php?title=Name_server_protocol). It's used to perform the translation between a nickname and a *ring_id*.

# Note: Differences with GNU/Ring

## User
A user for **RING** is a ring_id (in fact, a key pair... but here it's not important)

## Device
A device for **RING** is a daemon using the *ring_id* of a user.

## Multi-devices
If a user has multiple devices, they should be able to get messages and calls on all devices. Not like **RORI**. That's why one *ring_id* is sufficient here.

# Registration processus

See diagram here
![mermaid-diagram-20180326233850](https://user-images.githubusercontent.com/1888628/37945594-f34d445c-314e-11e8-95b1-6b5e8f79547d.png)

# Discovery

Now, we have an user `alice`, with 2 devices (`pc`, `android`). **RORI**'s name server will provides some endpoints. `/name/alice` will return the *ring id* of the `pc` or `android`. `/name/alice_pc` will return the id of `pc` and `/name/alice_android` the id of `android`.

# Unregister and remove devices

Alice have the ability to revoke a device or to remove her account. `/unregister` will remove all of its devices and remove `/name/alice` too. So someone will be able to re-register `alice`.
`/revoke_device` will revoke the current device and de-link it from her account  (or with a parameter, another device).

# Note
The `add_device` must only be able when recognized as `alice`. Nobody can add a device to another account.
An attacker can directly modify the database **RORI** side. This is not solved here. So *alice* must trust **RORI**.

# Current status:
+ [x] **RORI** automatically accepts requests and add contact from anyone.
+ [x] provide a name server
+ [x] register accounts
+ [x] register device
+ [x] revoke device from device
+ [x] unregister
+ [x] revoke device from another device
+ [x] register device from another device
+ [x] comments
+ [x] Link 2 devices under the same nickname
+ [x] mocks daemon
+ [x] unit tests database
+ [x] unit tests server
+ [x] unit tests manager
+ [x] unit tests API
+ [x] Write wiki page

**Comment by AmarOk1412** [comment]
Closed via b21915c9b2082fbcbb8c199edcecb0b41b266dc3
