### ISSUE TITLE
RORI base emotions

### ISSUE THREAD

**Issue by AmarOk1412** [AmarOk1412/rori_core#12]
**RORI** emotions uses the *Shaver et al. (2001)* system.

# Primary emotions

Primary emotions are stored into `rori.db` and are:
+ Love
+ Joy
+ Surprise
+ Anger
+ Sadness
+ Fear
And will be under the form of an integer between 0 and 100.

# Combinations

These six emotions can be combinated in any modules to form a full spectrum of emotions:
https://en.wikipedia.org/wiki/Contrasting_and_categorization_of_emotions#Parrott's_emotions_by_groups

# Current status:
+ [x] Add table into `rori.db`
+ [x] Add utils to change emotions in modules
+ [x] Add an example
+ [x] wiki page
+ [x] Update README.md
+ [x] Clean PR
