### ISSUE TITLE
Devices should be linked to supported types

### ISSUE THREAD

**Issue by AmarOk1412** [AmarOk1412/rori_core#23]
# Description

For now, modules are for `text/plain` datatypes.

But it's not perfect for a lot of modules. For example, if a client want to support orders for controlling the music on this device for example, we do not want to see some text on the user side.

# Implementation

Currently we use a similar systems for rori orders like `/register`. What RORI will see is:

```json
{
    "text/plain":"msg"
}
```

The idea is to support custom messages.

For example a client can be able to send messages like:
```json
{
    "music":"informations"
}
```

and RORI will try to launch a `music` module. But a module can also craft a message on a custom datatypes. The thing is, all clients will not be able to support all datatypes. So they should announce supported types for better result.

# Full example

1. **Device** announce to **RORI** that this device supports music datatypes.
2. **Device** send to **RORI**:
```json
{
    "text/plain":"play music"
}
```
3. **RORI** launch the music module which craft for **Device** (cause compatible) this message:
```json
{
    "music":"play random"
}
```
4. **Device** receives the order and launch a random music on the device.

# TODO List

+ [x] link devices to datatypes
+ [x] Add the possibility to add datatypes
+ [x] Add the ability to remove datatypes
+ [x] unit tests
+ [x] Music example
+ [x] Update wiki
+ [x] Update README.md
