### ISSUE TITLE
Add Scheduler to schedule modules

### ISSUE THREAD

**Issue by AmarOk1412** [AmarOk1412/rori_core#42]
Add a scheduler to allow scheduling modules like alarm, news, mail, etc

# Description

A Scheduler start a module with the parameters that the module needs. Jobs can be scheduled to run once or to repeat. The input is given by a database. Modules must be able to add/remove/update tasks in the scheduler.

# Tasks

+ [x] Design API for modules
+ [x] Create table in the db (id|module|argument|at|secs|mins|hours|day (string)|repeat (bool)
+ [x] Code add/remove/update/etc => to test
+ [x] If module crash, scheduler must not panic
+ [x] Clean todos
+ [x] Clean warnings
+ [x] Add tests
+ [x] Add documentation
